routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
    ], function () {


    Route::get('/', function () {
        return redirect()->route('login');
    });

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    /*
    /-------------
    /	Dashboard
    /-------------
     */

    Route::group(['namespace' => 'Dashboard', 'middleware' => ['auth', 'admin']], function () {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::resource('dashboard/roles', 'RolesController');
        Route::get('dashboard/roles/{role}/users/create', 'Roles\UsersController@create')->name('roles.users.create');
        Route::post('dashboard/roles/{role}/users', 'Roles\UsersController@store')->name('roles.users.store');

        Route::resource('dashboard/positions', 'PositionsController');
        Route::resource('dashboard/users', 'UsersController');
        Route::resource('dashboard/seasons', 'SeasonsController');
        Route::resource('dashboard/grades', 'GradesController');
        Route::resource('dashboard/regions', 'RegionsController');
        Route::resource('dashboard/districts', 'DistrictsController');
        Route::resource('dashboard/banks', 'BanksController');
        
        Route::resource('dashboard/primary-parties', 'PrimaryPartiesController');
        Route::get('dashboard/primary-parties/{primary_party}/groups', 'PrimaryParties\GroupsController@index')->name('dashboard.primary-parties.groups.index');
        
        Route::resource('dashboard/commodities', 'CommoditiesController');
        Route::resource('dashboard/licenses', 'LicensesController');
        Route::resource('dashboard/location', 'LocationController');
        Route::resource('dashboard/warehouses-owners', 'WarehousesOwnersController');
        Route::resource('dashboard/warehouse-operators', 'WarehouseOperatorsController');
        Route::resource('dashboard/warehouse-operator-directors', 'WarehouseOperatorDirectorsController');

        Route::get('dashboard/warehouses', 'WarehousesController@index')->name('dashboard.warehouses.index');
        Route::get('dashboard/warehouses/create', 'WarehousesController@create')->name('dashboard.warehouses.create');
        Route::post('dashboard/warehouses', 'WarehousesController@store')->name('dashboard.warehouses.store');
        Route::post('dashboard/warehouses/{warehouse}/storegrades', 'WarehousesController@storegrades')->name('dashboard.warehouses.storegrades');
        Route::get('dashboard/warehouses/{warehouse}', 'WarehousesController@show')->name('dashboard.warehouses.show');

        Route::resource('dashboard/main-parties', 'MainPartiesController');

        Route::get('dashboard/main-parties/{main_party}/members/create', 'MainParties\MembersController@create')->name('dashboard.main-parties.main-party.members.create');
        Route::post('dashboard/main-parties/{main_party}/members', 'MainParties\MembersController@store')->name('dashboard.main-parties.main-party.members.store');
    });

// Main Party
    Route::group(['namespace' => 'MainParty', 'middleware' => 'main.party'], function () {
        Route::get('main-parties/{main_party}', 'MainPartyController@show')->name('main-party.main-party.show');
        Route::get('main-parties/{main_party}/primary-parties', 'PrimaryPartyController@index')->name('main-party.main-party.primary-parties.index');
        Route::get('main-parties/{main_party}/primary-parties/create', 'PrimaryPartyController@create')->name('main-party.main-party.primary-parties.create');
        Route::post('main-parties/{main_party}/primary-parties', 'PrimaryPartyController@store')->name('main-party.main-party.primary-parties.store');
        Route::get('main-parties/{main_party}/primary-parties/{primary_party}', 'PrimaryPartyController@show')->name('main-party.main-party.primary-parties.show');

        Route::get('main-parties/{main_party}/members', 'MembersController@index')->name('main-party.main-party.members.index');
        Route::get('main-parties/{main_party}/members/create', 'MembersController@create')->name('main-party.main-party.members.create');
        Route::post('main-parties/{main_party}/members', 'MembersController@store')->name('main-party.main-party.members.store');

        Route::get('main-parties/{main_party}/primary-parties/{primary_party}/members/create', 'PrimaryParties\MembersController@create')->name('main-party.main-party.primary-parties.members.create');
        Route::post('main-parties/{main_party}/primary-parties/{primary_party}/members', 'PrimaryParties\MembersController@store')->name('main-party.main-party.primary-parties.members.store');
    });

// Primary Party
    Route::group(['namespace' => 'PrimaryParty', 'middleware' => ['auth', 'primary.party']], function () {

        Route::get('primary-parties', 'PrimaryPartyController@index')->name('primary-party.primary-party.index');
        Route::get('primary-parties/{primary_party}', 'PrimaryPartyController@show')->name('primary-party.primary-party.show');


        // Primary party members
        Route::get('primary-parties/{primary_party}/members', 'MembersController@index')->name('primary-party.primary-party.members.index');
        Route::get('primary-parties/{primary_party}/members/create', 'PrimaryPartyController@createMember')->name('primary-party.primary-party.members.create');
        Route::get('primary-parties/{primary_party}/members/{member}', 'MembersController@show')->name('primary-party.primary-party.members.show');
        Route::post('primary-parties/{primary_party}/members', 'PrimaryPartyController@storeMember')->name('primary-party.primary-party.members.store');
        Route::post('primary-parties/{primary_party}/members/add-existing', 'PrimaryPartyController@storeExistingMember')->name('primary-party.primary-party.members.storeExisting');

        // Primary party member items
        Route::get('primary-parties/{primary_party}/members/{member}/items', 'Members\ItemsController@index')->name('primary-party.primary-party.members.items.index');
        Route::get('primary-parties/{primary_party}/members/{member}/items/create', 'Members\ItemsController@create')->name('primary-party.primary-party.members.items.create');
        Route::post('primary-parties/{primary_party}/members/{member}/items', 'Members\ItemsController@store')->name('primary-party.primary-party.members.items.store');

        // Primary party group members
        Route::get('primary-parties/{primary_party}/groups/{group}/members', 'Groups\MembersController@index')->name('primary-party.primary-party.groups.members');
        Route::get('primary-parties/{primary_party}/groups/{group}/members/create', 'Groups\MembersController@create')->name('primary-party.primary-party.groups.members.create');
        Route::post('primary-parties/{primary_party}/groups/{group}/members', 'Groups\MembersController@store')->name('primary-party.primary-party.groups.members.store');

        // Primary party groups
        Route::get('primary-parties/{primary_party}/groups', 'GroupsController@index')->name('primary-party.primary-party.groups.index');
        Route::get('primary-parties/{primary_party}/groups/create', 'GroupsController@create')->name('primary-party.primary-party.groups.create');
        Route::get('primary-parties/{primary_party}/groups/{group}', 'GroupsController@show')->name('primary-party.primary-party.groups.show');
        Route::post('primary-parties/{primary_party}/groups', 'GroupsController@store')->name('primary-party.primary-party.groups.store');

        // Primary party group items
        Route::get('primary-parties/{primary_party}/groups/{show}/items', 'Groups\ItemsController@index')->name('primary-party.primary-party.groups.items.index');
        Route::get('primary-parties/{primary_party}/groups/{show}/items/create', 'Groups\ItemsController@create')->name('primary-party.primary-party.groups.items.create');
        Route::post('primary-parties/{primary_party}/groups/{show}/items', 'Groups\ItemsController@store')->name('primary-party.primary-party.groups.items.store');
    });

    //Farmer 
    Route::group(['namespace' => 'Farmer','middleware'=>'auth'],function(){

         
         Route::resource('farmer/primaryItems', 'PrimaryItemsController');
         Route::resource('farmer/secondaryItems', 'SecondaryItemsController');
    });
  

// Warehouse
    Route::group(['namespace' => 'Warehouse', 'middleware' => ['auth', 'director']], function () {
        Route::get('warehouses', 'WarehousesController@index')->name('warehouses.index');
        Route::get('warehouses/{warehouse}', 'WarehousesController@show')->name('warehouses.show');
        Route::get('warehouses/{warehouse}/details', 'WarehousesController@viewdetails')->name('warehouses.viewdetails');

        Route::get('warehouses/{warehouse}/items', 'ItemsController@index')->name('warehouses.items.index');
        Route::post('warehouses/{warehouse}/items', 'ItemsController@store')->name('warehouses.items.store');
        Route::get('warehouses/{warehouse}/items/create', 'ItemsController@create')->name('warehouses.items.create');
        Route::get('warehouses/{warehouse}/items/{item}/receipts/create', 'ItemReceiptsController@create')->name('warehouses.items.receipts.create');
        
        Route::get('warehouses/{warehouse}/items/{item}', 'ItemsController@show')->name('warehouses.items.show');
        

app/Http/Controllers/Dashboard/BanksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Bank;
use Illuminate\Http\Request;

class BanksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banks = Bank::latest()->get();
        return view('dashboard.banks.index', compact('banks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.banks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'short_name' => 'required',
            'full_name' => 'required',
        ]);

        $bank = new Bank();
        $bank->short_name = $request->input('short_name');
        $bank->full_name = $request->input('full_name');
        $bank->remark = $request->input('remarks');
        $bank->save();

        flash("Bank successfully saved")->success()->important();

        return redirect('dashboard/banks');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Bank $bank)
    {
        return view('dashboard.banks.edit', compact('bank'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bank $bank)
    {
        $this->validate($request, [
            'short_name' => 'required',
            'full_name' => 'required',
        ]);

        $bank->update([
            'short_name' => $request->short_name,
            'full_name' => $request->full_name,
            'remark' => $request->remarks
        ]);

        return redirect()->route('banks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bank $bank)
    {
        $bank->delete();

        flash('Success')->success();

        return redirect()->route('banks.index');
    }
}

app/Http/Controllers/Dashboard/CommoditiesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Commodity;
use Illuminate\Http\Request;

class CommoditiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $commodities = Commodity::latest()->get();

        return view('Dashboard.commodities.index', compact('commodities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Dashboard.commodities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'status' => 'required',
        ]);

        $commodity = new Commodity;
        $commodity->name = $request->input('name');
        $commodity->description = $request->input('description');
        $commodity->status = $request->input('status');
        $commodity->save();

        flash('Commodity saved successful.')->success()->important();

        return redirect('dashboard/commodities');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Bank;
use App\Models\Commodity;
use App\Models\District;
use App\Models\GradeDetail;
use App\Models\Item;
use App\Models\ItemOwnership;
use App\Models\License;
use App\Models\Loan;
use App\Models\Location;
use App\Models\MainParty;
use App\Models\Position;
use App\Models\PrimaryItem;
use App\Models\PrimaryParty;
use App\Models\PrimaryPartyGroup;
use App\Models\Region;
use App\Models\Role;
use App\Models\SeasonDetail;
use App\Models\User;
use App\Models\Warehouse;
use App\Models\WarehouseOperator;
use App\Models\WarehouseOperatorDirector;
use App\Models\WarehouseOwner;

class DashboardController extends Controller
{
    public function index()
    {
        $stats = [
            'banks' => Bank::count(),
            'commodities' => Commodity::count(),
            'districts' => District::count(),
            'gradeDetails' => GradeDetail::count(),
            'items' => Item::count(),
            'itemOwnerships' => ItemOwnership::count(),
            'licenses' => License::count(),
            'loans' => Loan::count(),
            'locations' => Location::count(),
            'mainParties' => MainParty::count(),
            'positions' => Position::count(),
            'primaryItems' => PrimaryItem::count(),
            'primaryParties' => PrimaryParty::count(),
            'primaryPartyGroups' => PrimaryPartyGroup::count(),
            'regions' => Region::count(),
            'roles' => Role::count(),
            'seasonDetails' => SeasonDetail::count(),
            'users' => User::count(),
            'warehouses' => Warehouse::count(),
            'warehouseOperators' => WarehouseOperator::count(),
            'warehouseOperatorDirectors' => WarehouseOperatorDirector::count(),
            'warehouseOwners' => WarehouseOwner::count(),

        ];

        return view('dashboard.dashboard.index', compact('stats'));
    }
}

app/Http/Controllers/Dashboard/PositionsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Position;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PositionsController extends Controller
{
    public function index()
    {
    	$positions = Position::latest()->get();
    	return view('dashboard.positions.index',compact('positions'));
    }
    public function create()
    {
     return view('dashboard.positions.create');
    }
    public function store(Request $request)
    {
    	$this->validate($request,[
            'name' => 'required',
            'display_name' => 'required',
    		]);
        $position = new Position;
        $position->name = $request->input('name');
        $position->display_name = $request->input('display_name');
        $position->description = $request->input('description');
        $position->save();

        flash('Position saved successful')->success()->important();

        return redirect()->route('positions.index');

    }
}

resources/views/dashboard/banks/_form.blade.php
<div class="form-group">
    <label for="full_name">Full name</label>
    <input type="text" name="full_name" id="full_name" value="{{ $bank->full_name or old('full_name') }}" class="form-control" required>
</div>
<div class="form-group">
    <label for="short_name">Short name</label>
    <input type="text" name="short_name" id="short_name" value="{{ $bank->short_name or old('short_name') }}" class="form-control" required>
</div>
<div class="form-group">
    <label for="remarks">Remarks</label>
    <textarea name="remarks" id="remaks" rows="5" class="form-control">{{ $bank->remarks or old('remarks') }}</textarea>
</div>

resources/views/dashboard/banks/create.blade.php
@extends('layouts.dashboard')

@section('title','Create bank');

@section('content')
    <div class="container-fluid">
   <div class="container-fluid">
    <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create new bank</h1>
    </div>
    </div>
    <!-- /.col-lg-12 -->
        <div class="row">
            <div class="col-lg-12">
                <div class="">
                  

                    <div class="panel-body">

                        @include('errors.list')

                        <form action="{{ route('banks.store') }}" method="post">
                            {{ csrf_field() }}

                            @include('dashboard.banks._form')

                            <button type="submit" class="btn btn-primary">Submit</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/banks/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Edit ' . $bank->full_name);

@section('content')
    <div class="container-fluid">
   <div class="container-fluid">
    <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit {{ $bank->full_name }}</h1>
    </div>
    </div>
    <!-- /.col-lg-12 -->
        <div class="row">
            <div class="col-lg-12">
                <div class="">
                  

                    <div class="panel-body">

                        @include('errors.list')

                        <form action="{{ route('banks.update', $bank->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}

                            @include('dashboard.banks._form')

                            <button type="submit" class="btn btn-primary">Update</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/banks/index.blade.php
@extends('layouts.dashboard')

@section('title','Banks');

@section('content')


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Banks</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
              All Banks
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>SN</th>
                            <th>Short name</th>
                            <th>Full name</th>
                            <th>Created</th>
                            <th>Updated</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $i = 1 @endphp
                        @foreach($banks as $bank)
                        <tr>
                            <td>{{ $i++ }}.</td>
                            <td>{{ $bank->short_name }}</td>
                            <td>{{ $bank->full_name }}</td>
                            <td>{{ $bank->created_at->toFormattedDateString() }}</td>
                            <td>{{ $bank->updated_at->toFormattedDateString() }}</td>
                            <td>
                                <a href="{{ route('banks.edit', $bank->id) }}" class="btn btn-success"><i class="fa fa-edit"></i> Edit</a>
                            </td>
                            <td>
                                <a class="btn btn-danger" data-toggle="modal" href='#delete-bank-{{ $bank->id }}'><i class="fa fa-trash"></i> Delete</a>
                                <div class="modal fade" id="delete-bank-{{ $bank->id }}">
                                    <div class="modal-dialog">
                                        <form action="{{ route('banks.destroy', $bank->id) }}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}

                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                    <h4 class="modal-title">Deleting {{ $bank->full_name }}</h4>
                                                </div>
                                                <div class="modal-body">
                                                    Delete <strong>{{ $bank->full_name }}</strong>?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                                                </div>
                                            </div>
                                                                                    
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach                       
                    </tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer">
                <a href="{{ route('banks.create') }}" class="btn btn-primary">New</a>
            </div>            
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

@endsection